# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json
PackageIdentifier: Unixwin.Niubash
PackageVersion: 1.2.1
InstallerType: inno
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/unixwin/niubash/releases/download/v1.2.1/niubash-v1.2.1-win-x64-setup.exe
    InstallerSha256: F856CA9D51DE9847243FEC3E82D9BB0DE5AF5A4F7B0B570C7EDFECA6DFB386F6
    InstallerSwitches:
      Silent: /VERYSILENT /NORESTART
      SilentWithProgress: /SILENT /NORESTART
    Scope: user
  - Architecture: arm64
    InstallerUrl: https://github.com/unixwin/niubash/releases/download/v1.2.1/niubash-v1.2.1-win-arm64-setup.exe
    InstallerSha256: F9228ECD7B11A801E867E58D93A7168E38D5551F048A79B169728BDEFA312F4A
    InstallerSwitches:
      Silent: /VERYSILENT /NORESTART
      SilentWithProgress: /SILENT /NORESTART
    Scope: user
ManifestType: installer
ManifestVersion: 1.10.0
