# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json
PackageIdentifier: Unixwin.Niubash
PackageVersion: 1.3.0
InstallerType: inno
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/unixwin/niubash/releases/download/v1.3.0/niubash-v1.3.0-win-x64-setup.exe
    InstallerSha256: 1CC56AAEA3F244795FC3E0C812C311374C326752AE075F9C108904F0E38E19A9
    InstallerSwitches:
      Silent: /VERYSILENT /NORESTART
      SilentWithProgress: /SILENT /NORESTART
    Scope: user
  - Architecture: arm64
    InstallerUrl: https://github.com/unixwin/niubash/releases/download/v1.3.0/niubash-v1.3.0-win-arm64-setup.exe
    InstallerSha256: 5700557572A1D2A5E35B8008E021F6B6F3BB657061E0FE5755E8E04C29CDF19F
    InstallerSwitches:
      Silent: /VERYSILENT /NORESTART
      SilentWithProgress: /SILENT /NORESTART
    Scope: user
ManifestType: installer
ManifestVersion: 1.10.0
