# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json
PackageIdentifier: Unixwin.Niubash
PackageVersion: 1.2.5
InstallerType: inno
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/unixwin/niubash/releases/download/v1.2.5/niubash-v1.2.5-win-x64-setup.exe
    InstallerSha256: C803307363545624C7429F1B6CC68B797D41011699CCF5D65AC845A59261C7A4
    InstallerSwitches:
      Silent: /VERYSILENT /NORESTART
      SilentWithProgress: /SILENT /NORESTART
    Scope: user
  - Architecture: arm64
    InstallerUrl: https://github.com/unixwin/niubash/releases/download/v1.2.5/niubash-v1.2.5-win-arm64-setup.exe
    InstallerSha256: 708DFB61D477BF310223622E5EB07D22C8BA6C7460A99FB076D59DE13D0E0EFF
    InstallerSwitches:
      Silent: /VERYSILENT /NORESTART
      SilentWithProgress: /SILENT /NORESTART
    Scope: user
ManifestType: installer
ManifestVersion: 1.10.0
