# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json
PackageIdentifier: Unixwin.Niubash
PackageVersion: 1.2.3
InstallerType: inno
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/unixwin/niubash/releases/download/v1.2.3/niubash-v1.2.3-win-x64-setup.exe
    InstallerSha256: DCA8C5430F1B5C2A5839DA6685AF0F38ED9127E1D57B44BC03580E7C566CAAD5
    InstallerSwitches:
      Silent: /VERYSILENT /NORESTART
      SilentWithProgress: /SILENT /NORESTART
    Scope: user
  - Architecture: arm64
    InstallerUrl: https://github.com/unixwin/niubash/releases/download/v1.2.3/niubash-v1.2.3-win-arm64-setup.exe
    InstallerSha256: 67EC6FB0A7A1131AC9853B7D749A827A1184CA7FB13A5064583BD8838111E2DA
    InstallerSwitches:
      Silent: /VERYSILENT /NORESTART
      SilentWithProgress: /SILENT /NORESTART
    Scope: user
ManifestType: installer
ManifestVersion: 1.10.0
